"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

# Get data files
for folder in "images", "sounds", "levels":
    files = [os.path.join(folder, name) for name in os.listdir(folder)]
    DATA_FILES.append((folder, files))

setup(
    name="Mac Explorer",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
